/*
@title: keyboard for sprig
@author: mrdarip
@tags: []
@addedOn: 2024-00-00
*/

words = ("hello world this is a sample text with some words the user can type").split(" ")
characters = ("abcdefghijklmnopqrstuvwxyz").split("")

currentWord = ""
currentText = []
possibleWords = []
charactersOnEachButton = [[],[],[],[],[],[],[],[]]


const player = "p"

setLegend(
  [ player, bitmap`
................
................
.......000......
.......0.0......
......0..0......
......0...0.0...
....0003.30.0...
....0.0...000...
....0.05550.....
......0...0.....
.....0....0.....
.....0...0......
......000.......
......0.0.......
.....00.00......
................` ]
)

setSolids([])

let level = 0
const levels = [
  map`
.........p
..........
..........
..........
..........
..........
..........
..........`
]

setMap(levels[level])

setPushables({
  [ player ]: []
})

onInput("s", () => {
  getFirst(player).y += 1
})

afterInput(() => {
  
})